### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by knutole** [mapic/shiny#1]
### Floating License server, stand-alone container
- [x] Floating Server not part of compose. Will run stand-alone, since it shouldn't be restarted often.
- [x] Create Docker network: `shiny-network`

### Containers
- [x] use Docker network: `shiny-network` 
- [x] nginx container, for reverse-proxying: Auth0, public- and private access.
    - [x] create `mapic/shiny-nginx` image which includes certbot
    - [x] [configure](https://www.r-bloggers.com/shiny-server-series-part-2-running-shiny-on-multiple-ports/) for certbot, shiny, auth0
- [x] Shiny Server Pro container 
    - [x] create `mapic/shiny-server-pro`
    - [x] use config file
    - [x] configure SSL [certbot](https://www.r-bloggers.com/shiny-server-series-part-3-adding-ssl-encryption/)
- [x] Auth0 nodejs proxy https://github.com/mapic/shiny-auth0.docker
    - [x] create `mapic/shiny-auth0`
    - [x] add config to docker-compose environment
    - [x] create account @ auth0.com
    - [x] create account @ twilio
    - [x] create apps and connect
    - [x] add password-less login: email magic link, SMS or TOTP with Auth0 ([guide](https://www.r-bloggers.com/shiny-server-series-part-4-adding-user-authentication-using-auth0/))

### Docker Hub, Travis, SSLLabs
- [x] add images to Docker Hub
    - [x] mapic/shiny-auth0
    - [x] mapic/shiny-floating-license-server
    - [x] mapic/shiny-server-pro
    - [x] mapic/shiny-nginx (todo!)
- [x] Add Travis/Docker Build tests for builds
- [x] add build repos to Docker Hub (with Dockerfile)
- [x] SSLLabs server test (results [here](https://www.ssllabs.com/ssltest/analyze.html?d=cloud.ngi.no&hideResults=on))

### Uploading
- [x] define way to add data to shiny
- [x] implement
- [x] sftp docker container with shared volume
- [ ] next iteration: automatically `chown` `shiny:www-data`

### Cleanup
- [x] remove stale docker images & containers
- [x] close unused ports

### Other
- [x] gdpr
- [x] shiny/editor access
- [x] add guest accounts to auth0.com and twilio.com
- [x] write documentation
- [x] write delivery report
- [x] `t3.medium`

### MFA
- [x] email/user + sms (OR -> seems to remember email login now, so only sms necessary after first time. good enough?)

**Comment by knutole** [comment]
## Passswordless Login
### Hosted Pages -> Login Page
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Sign In with Auth0</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>

  <!--[if IE 8]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/ie8/0.2.5/ie8.js"></script>
  <![endif]-->

  <!--[if lte IE 9]>
  <script src="https://cdn.auth0.com/js/base64.js"></script>
  <script src="https://cdn.auth0.com/js/es5-shim.min.js"></script>
  <![endif]-->

  <script src="https://cdn.auth0.com/js/lock/11.3/lock.min.js"></script>
  <script>
    // Decode utf8 characters properly
    var config = JSON.parse(decodeURIComponent(escape(window.atob('@@config@@'))));
    config.extraParams = config.extraParams || {};
    var connection = config.connection;
    var prompt = config.prompt;
    var languageDictionary;
    var language;
    
    if (config.dict && config.dict.signin && config.dict.signin.title) {
      languageDictionary = { title: config.dict.signin.title };
    } else if (typeof config.dict === 'string') {
      language = config.dict;
    }
    var loginHint = config.extraParams.login_hint;
    
    // Available Lock configuration options: https://auth0.com/docs/libraries/lock/v11/configuration
    var lock = new Auth0LockPasswordless(config.clientID, config.auth0Domain, {
      auth: {
        redirectUrl: config.callbackURL,
        responseType: (config.internalOptions || {}).response_type ||
          (config.callbackOnLocationHash ? 'token' : 'code'),
        params: config.internalOptions
      },
  
      // additional configuration needed for custom domains
      /* 
      configurationBaseUrl: config.clientConfigurationBaseUrl,
      overrides: {
        __tenant: config.auth0Tenant,
        __token_issuer: 'auth.cloud.ngi.no'
      }, 
      
      */ 
      assetsUrl:  config.assetsUrl,
      //allowedConnections: connection ? [connection] : null,
      allowedConnections: ['email'],
      passwordlessMethod: 'link',
      rememberLastLogin: !prompt,
      language: language,
      languageDictionary: languageDictionary,
      theme: {
        logo: 'https://i.imgur.com/0gXMoc9.png',
        //primaryColor:    'green'
      },
      prefill: loginHint ? { email: loginHint, username: loginHint } : null,
      closable: false,
      defaultADUsernameFromEmailPrefix: false,
      // uncomment if you want small buttons for social providers
      // socialButtonStyle: 'small'
    });

    lock.show();
    console.log('test sms!');
  </script>
</body>
</html>
```

**Comment by knutole** [comment]
## Email/password login
### Hosted Pages -> Login Page
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Sign In with Auth0</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>

  <!--[if IE 8]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/ie8/0.2.5/ie8.js"></script>
  <![endif]-->

  <!--[if lte IE 9]>
  <script src="https://cdn.auth0.com/js/base64.js"></script>
  <script src="https://cdn.auth0.com/js/es5-shim.min.js"></script>
  <![endif]-->

  <script src="https://cdn.auth0.com/js/lock/11.3/lock.min.js"></script>
  <script>
    // Decode utf8 characters properly
    var config = JSON.parse(decodeURIComponent(escape(window.atob('@@config@@'))));
    config.extraParams = config.extraParams || {};
    var connection = config.connection;
    var prompt = config.prompt;
    var languageDictionary;
    var language;
    
    if (config.dict && config.dict.signin && config.dict.signin.title) {
      languageDictionary = { title: config.dict.signin.title };
    } else if (typeof config.dict === 'string') {
      language = config.dict;
    }
    var loginHint = config.extraParams.login_hint;
    
    // Available Lock configuration options: https://auth0.com/docs/libraries/lock/v11/configuration
    var lock = new Auth0Lock(config.clientID, config.auth0Domain, {
      auth: {
        redirectUrl: config.callbackURL,
        responseType: (config.internalOptions || {}).response_type ||
          (config.callbackOnLocationHash ? 'token' : 'code'),
        params: config.internalOptions
      },
      /* additional configuration needed for custom domains
      configurationBaseUrl: config.clientConfigurationBaseUrl,
      overrides: {
        __tenant: config.auth0Tenant,
        __token_issuer: 'YOUR_CUSTOM_DOMAIN'
      }, */
      assetsUrl:  config.assetsUrl,
      allowedConnections: connection ? [connection] : null,
      rememberLastLogin: !prompt,
      language: language,
      languageDictionary: languageDictionary,
      theme: {
        logo:           'https://i.imgur.com/0gXMoc9.png',
        //primaryColor:    'green'
      },
      prefill: loginHint ? { email: loginHint, username: loginHint } : null,
      closable: false,
      defaultADUsernameFromEmailPrefix: false,
      // uncomment if you want small buttons for social providers
      // socialButtonStyle: 'small'
    });

    lock.show();
  </script>
</body>
</html>
```
