### ISSUE TITLE
Open Source Shiny Server

### ISSUE THREAD

**Issue by knutole** [mapic/shiny#2]
# Shiny Pro vs. Open Source
## Both
- [x] Host multiple applications simultaneously, each at its own URL.
- [x] Support web browsers that don't support WebSocket, including Internet Explorer 8 & 9.
- [x] Enable system users to develop and manage their own Shiny applications.
- [x] Ensure that R processes that crash or are terminated automatically restart for the next user requesting the application.

## Pro Only
- [x] Ensure your applications are protected and can only be accessed by specific, authenticated users. **(We can do this ourselves using Auth0.com)**
- [x] Securely encrypt data being sent to and from your applications using SSL. **(We can do this ourselves using Nginx and Let's Encrypt.)**
- [ ] Scale a Shiny application to support many users by empowering a Shiny application to be backed by multiple R Shiny processes simultaneously.
- [ ] Gain insight into the performance and usage of your Shiny applications by monitoring them using a web dashboard. (aka the Admin panel)
- [ ] Understand and manage current and historical application resource utilization to better configure and optimize your applications.
- [ ] Fine-tune the resources devoted to each user of an application by configuring multi-process Shiny applications based on the number of concurrent sessions.
- [ ] Monitor the health of your Shiny Server using the health check endpoint.

## Conclusion
Det eneste potensielt relevante som vi mangler med Open-Source versjonen, er `admin-siden` (som inneholder litt generell statistikk) og `multi-process R`, så vidt jeg kan se. Hvis dere kan klare dere uten dette, så bør Shiny Server Open-Source fungere fint!

## References
https://www.rstudio.com/products/shiny/shiny-server/

**Comment by knutole** [comment]
## Shiny Pro vs. Open Source
### Both
- [x] Host multiple applications simultaneously, each at its own URL.
- [x] Support web browsers that don't support WebSocket, including Internet Explorer 8 & 9.
- [x] Enable system users to develop and manage their own Shiny applications.
- [x] Ensure that R processes that crash or are terminated automatically restart for the next user requesting the application.

### Pro Only
- [ ] Ensure your applications are protected and can only be accessed by specific, authenticated users. **(We can do this ourselves using Auth0.com)**
- [ ] Securely encrypt data being sent to and from your applications using SSL. **(We can do this ourselves.)**
- [ ] Scale a Shiny application to support many users by empowering a Shiny application to be backed by multiple R Shiny processes simultaneously.
- [ ] Gain insight into the performance and usage of your Shiny applications by monitoring them using a web dashboard.
- [ ] Understand and manage current and historical application resource utilization to better configure and optimize your applications.
- [ ] Fine-tune the resources devoted to each user of an application by configuring multi-process Shiny applications based on the number of concurrent sessions.
- [ ] Monitor the health of your Shiny Server using the health check endpoint.

**Comment by knutole** [comment]
## S3
Klart til mandag:
- [x] opplasting til S3 fra anywhere, med keys
- [x] nedlasting til Shiny-EC2 til `ngi`
- [x] med IP til både prod og staging

## Versioning
- [x] versjoer av RStudio osv. 

## staging server, open source
- [x] open source versjon av shiny

**Comment by knutole** [comment]
## todo
### general
- [x] update architecture png
- [x] install latest R package list
- [x] ~add IP to S3 whitelist~
- [x] ensure email verification is correct
- [x] document more thoroughly install / maintenance of shiny server setup
- [x] clean up auth docker repo namespace
- [x] clean up sftp docker namespace
- [ ] RStudio IDE @ AWS ?
- [x] websocket pings
- [x] travis/hub for all images (incl. sftp)

### prod
- [x] setup `prod` shiny server @ cloud.ngi.no
- [x] configure auth0.com for domain

### staging
- [x] setup `staging` shiny server @ staging.ngi.no
- [x] add DNS entries for server + auth0
- [x] configure auth0.com for domain
- [x] create tenant @ auth0.com 
- [ ] do we need MFA for staging?

### sandbox
- [x] setup `sandbox` shiny server @ sandbox.ngi.no
- [x] add DNS entries for server + auth0
- [x] configure auth0.com for domain
- [x] create tenant @ auth0.com 
- [ ] do we need MFA for dev?
